#!/usr/bin/env node
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CA_ENV_KEYS,
  fetchContainerConfig,
  isOnecliProxy,
  onecliPaths,
  parseProxyUrl,
  probeProxy,
  readHookInput,
  resolveApiHost,
  resolveApiKey,
  shellQuote,
  writeCABundle,
  writeFilePrivate,
  type ContainerConfig,
} from "../shared/runtime.mjs";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = process.env.PLUGIN_ROOT || dirname(SCRIPT_DIR);
const HELPER_PATH = join(PLUGIN_ROOT, "bin", "onecli-cursor-env.mjs");
const NODE_PATH = process.execPath;

const ACTIVE_CONTEXT = [
  "OneCLI Gateway active. Call external APIs directly (plain curl/gh); requests route through the gateway and credentials are injected automatically. Never add Authorization headers.",
  "On errors: connect_url → show it to the user and retry after they connect; blocked_by_policy → report the rule, do not circumvent; rate_limited → wait retry_after_secs. Details: onecli-gateway skill.",
].join(" ");

const SETUP_CONTEXT =
  "OneCLI Gateway: installed but not configured. Tell the user to invoke the onecli-setup skill. Do not attempt external API requests until configured.";

interface LoaderInputs {
  pluginRoot: string;
  helperPath: string;
  nodePath: string;
  sessionId: string;
}

function buildLoaderContent({ pluginRoot, helperPath, nodePath, sessionId }: LoaderInputs): string {
  const sessionLine = sessionId
    ? `export ONECLI_CURSOR_SESSION_ID=${shellQuote(sessionId)}`
    : "unset ONECLI_CURSOR_SESSION_ID";

  return [
    "# Generated by the OneCLI Cursor plugin.",
    "# This loader contains no gateway credential; sourcing it fetches fresh exports.",
    `export ONECLI_CURSOR_PLUGIN_ROOT=${shellQuote(pluginRoot)}`,
    sessionLine,
    `eval "$(ONECLI_CURSOR_PLUGIN_ROOT="$ONECLI_CURSOR_PLUGIN_ROOT" ONECLI_CURSOR_SESSION_ID="\${ONECLI_CURSOR_SESSION_ID:-}" ${shellQuote(nodePath)} ${shellQuote(helperPath)} --format sh)"`,
    "",
  ].join("\n");
}

function writeLoaderFile(sessionId: string): string {
  const paths = onecliPaths();
  const content = buildLoaderContent({
    pluginRoot: PLUGIN_ROOT,
    helperPath: HELPER_PATH,
    nodePath: NODE_PATH,
    sessionId,
  });
  writeFilePrivate(paths.envPath, content);
  return paths.envPath;
}

function buildEnvObject(config: ContainerConfig, caBundlePath: string): Record<string, string> {
  const raw = config && typeof config.env === "object" && config.env !== null ? config.env : {};
  const env: Record<string, string> = {};

  for (const [key, value] of Object.entries(raw)) {
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    if (CA_ENV_KEYS.includes(key)) continue;
    env[key] = value;
  }

  if (config?.caCertificate) {
    for (const key of CA_ENV_KEYS) {
      env[key] = caBundlePath;
    }
  }

  env.GIT_TERMINAL_PROMPT = "0";
  env.GIT_HTTP_PROXY_AUTHMETHOD = "basic";
  env.NODE_USE_ENV_PROXY = "1";
  return env;
}

function emit(output: { env?: Record<string, string>; additional_context?: string }): void {
  if (Object.keys(output).length > 0) {
    process.stdout.write(JSON.stringify(output));
  }
}

async function main(): Promise<void> {
  const hookInput = await readHookInput();
  const sessionId = typeof hookInput.session_id === "string" ? hookInput.session_id : "";
  const paths = onecliPaths();
  const envPath = writeLoaderFile(sessionId);

  if (isOnecliProxy(process.env.HTTPS_PROXY)) {
    process.stderr.write("onecli: gateway already active.\n");
    emit({ additional_context: ACTIVE_CONTEXT });
    return;
  }

  const apiKey = resolveApiKey(paths);
  if (!apiKey) {
    process.stderr.write("onecli: no API key found.\n");
    emit({ additional_context: SETUP_CONTEXT });
    return;
  }

  const apiHost = resolveApiHost(paths);
  const headers: Record<string, string> = {};
  if (sessionId) headers["X-OneCLI-Cursor-Session-Id"] = sessionId;

  const result = await fetchContainerConfig(apiHost, apiKey, { headers });
  if (!result.ok) {
    if (result.reason === "unauthorized") {
      emit({
        additional_context:
          "OneCLI: API key is invalid or expired. Tell the user to run the onecli-setup skill. External API requests will fail this session.",
      });
      return;
    }
    emit({
      additional_context:
        "OneCLI gateway config could not be fetched. Use the onecli-status skill to diagnose. The loader file is ready for per-command sourcing.",
    });
    process.stderr.write(`onecli: gateway loader written to ${envPath}.\n`);
    return;
  }

  const config = result.config;
  const proxyUrl = config.env.HTTPS_PROXY || config.env.https_proxy;
  if (proxyUrl) {
    const parsed = parseProxyUrl(proxyUrl);
    if (parsed) {
      const reachable = await probeProxy(parsed.host, parsed.port);
      if (!reachable) {
        emit({
          additional_context:
            "OneCLI gateway proxy is unreachable. Use the onecli-status skill to diagnose. Per-command sourcing may still work once the proxy is available.",
        });
        process.stderr.write(`onecli: gateway loader written to ${envPath}.\n`);
        return;
      }
    }
  }

  if (config.caCertificate) {
    writeCABundle(config.caCertificate, paths);
  }

  const env = buildEnvObject(config, paths.caBundlePath);
  if (sessionId) {
    env.ONECLI_CURSOR_SESSION_ID = sessionId;
  }

  process.stderr.write(`onecli: gateway loader written to ${envPath}.\n`);
  emit({ env, additional_context: ACTIVE_CONTEXT });
}

main().catch((err) => {
  process.stderr.write(
    `onecli: plugin error: ${err instanceof Error ? err.message : String(err)}\n`
  );
});
