#!/usr/bin/env node
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  isOnecliProxy,
  onecliPaths,
  readHookInput,
  resolveApiKey,
  shellQuote,
  writeFilePrivate,
} from "../shared/runtime.mjs";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = process.env.PLUGIN_ROOT || dirname(SCRIPT_DIR);
const HELPER_PATH = join(PLUGIN_ROOT, "bin", "onecli-codex-env.mjs");
const NODE_PATH = process.execPath;

interface LoaderInputs {
  pluginRoot: string;
  helperPath: string;
  nodePath: string;
  sessionId: string;
}

function buildLoaderContent({ pluginRoot, helperPath, nodePath, sessionId }: LoaderInputs): string {
  const sessionLine = sessionId
    ? `export ONECLI_CODEX_SESSION_ID=${shellQuote(sessionId)}`
    : "unset ONECLI_CODEX_SESSION_ID";

  return [
    "# Generated by the OneCLI Codex plugin.",
    "# This loader contains no gateway credential; sourcing it fetches fresh exports.",
    `export ONECLI_CODEX_PLUGIN_ROOT=${shellQuote(pluginRoot)}`,
    sessionLine,
    `eval "$(ONECLI_CODEX_PLUGIN_ROOT="$ONECLI_CODEX_PLUGIN_ROOT" ONECLI_CODEX_SESSION_ID="\${ONECLI_CODEX_SESSION_ID:-}" ${shellQuote(nodePath)} ${shellQuote(helperPath)} --format sh)"`,
    "",
  ].join("\n");
}

function writeLoaderFile(sessionId: string): string {
  const paths = onecliPaths();
  const content = buildLoaderContent({
    pluginRoot: PLUGIN_ROOT,
    helperPath: HELPER_PATH,
    nodePath: NODE_PATH,
    sessionId,
  });
  writeFilePrivate(paths.envPath, content);
  return paths.envPath;
}

function printSetupRequired(envPath: string): void {
  process.stdout.write(
    [
      "# OneCLI Gateway - Setup Required",
      "",
      `Gateway loader file: ${envPath}`,
      "",
      "The OneCLI Codex plugin is installed but no API key was found.",
      "Use the onecli-setup skill to configure `~/.onecli/credentials/api-key`.",
      "After setup, start a new Codex thread or rerun this hook.",
      "",
    ].join("\n")
  );
}

function printActiveMessage(envPath: string): void {
  process.stdout.write(
    [
      "# OneCLI Gateway Active",
      "",
      `Gateway loader file: ${envPath}`,
      "",
      "The loader file contains no live gateway credential. Sourcing it runs the OneCLI helper, fetches fresh gateway exports, and applies them to that shell command.",
      "",
      "The plugin also includes a conservative PreToolUse hook that auto-sources supported outbound Bash commands. If you need to source manually, use:",
      "",
      "```bash",
      '. ~/.onecli/env.sh && curl -s "https://api.github.com/user"',
      "```",
      "",
      "Rules:",
      "- Prefer direct HTTP requests through curl/fetch for connected services.",
      "- Do not add Authorization headers manually; the gateway injects credentials.",
      "- If a response includes `connect_url`, show it to the user and retry after they connect.",
      "- If a response includes `blocked_by_policy`, report the policy and do not circumvent it.",
      "- If a response includes `retry_after_secs`, wait before retrying.",
      "- Use the onecli-gateway skill for detailed gateway behavior.",
      "",
    ].join("\n")
  );
}

async function main(): Promise<void> {
  const hookInput = await readHookInput();
  const sessionId = typeof hookInput.session_id === "string" ? hookInput.session_id : "";
  const envPath = writeLoaderFile(sessionId);

  if (isOnecliProxy(process.env.HTTPS_PROXY)) {
    process.stderr.write("onecli: gateway already active.\n");
    printActiveMessage(envPath);
    return;
  }

  const apiKey = resolveApiKey();
  if (!apiKey) {
    process.stderr.write("onecli: no API key found.\n");
    printSetupRequired(envPath);
    return;
  }

  process.stderr.write("onecli: gateway loader written.\n");
  printActiveMessage(envPath);
}

main().catch((err) => {
  process.stderr.write(
    `onecli: plugin error - ${err instanceof Error ? err.message : String(err)}\n`
  );
});
