#!/usr/bin/env node
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  isOnecliProxy,
  onecliPaths,
  readHookInput,
  resolveApiKey,
  shellQuote,
  writeFilePrivate,
} from "../shared/runtime.mjs";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = process.env.PLUGIN_ROOT || dirname(SCRIPT_DIR);
const HELPER_PATH = join(PLUGIN_ROOT, "bin", "onecli-codex-env.mjs");
const NODE_PATH = process.execPath;

interface LoaderInputs {
  pluginRoot: string;
  helperPath: string;
  nodePath: string;
  sessionId: string;
}

function buildLoaderContent({ pluginRoot, helperPath, nodePath, sessionId }: LoaderInputs): string {
  const sessionLine = sessionId
    ? `export ONECLI_CODEX_SESSION_ID=${shellQuote(sessionId)}`
    : "unset ONECLI_CODEX_SESSION_ID";

  return [
    "# Generated by the OneCLI Codex plugin.",
    "# This loader contains no gateway credential; sourcing it fetches fresh exports.",
    `export ONECLI_CODEX_PLUGIN_ROOT=${shellQuote(pluginRoot)}`,
    sessionLine,
    `eval "$(ONECLI_CODEX_PLUGIN_ROOT="$ONECLI_CODEX_PLUGIN_ROOT" ONECLI_CODEX_SESSION_ID="\${ONECLI_CODEX_SESSION_ID:-}" ${shellQuote(nodePath)} ${shellQuote(helperPath)} --format sh)"`,
    "",
  ].join("\n");
}

function writeLoaderFile(sessionId: string): string {
  const paths = onecliPaths();
  const content = buildLoaderContent({
    pluginRoot: PLUGIN_ROOT,
    helperPath: HELPER_PATH,
    nodePath: NODE_PATH,
    sessionId,
  });
  writeFilePrivate(paths.envPath, content);
  return paths.envPath;
}

function printSetupRequired(): void {
  process.stdout.write(
    [
      "OneCLI Gateway: installed but not configured — external API calls will fail.",
      "Run the onecli-setup skill to configure the API key, then start a new thread.",
      "",
    ].join("\n")
  );
}

function printActiveMessage(): void {
  // Codex renders this context verbatim in the thread, so keep it terse.
  // Detailed behavior (manual sourcing, error shapes) lives in the
  // onecli-gateway skill. Do NOT suggest sourcing env.sh here: agents that
  // prefix commands themselves bypass the PreToolUse auto-allow rewrite and
  // trigger avoidable approval prompts.
  process.stdout.write(
    [
      "OneCLI Gateway active. Call external APIs directly (plain `curl`/`gh`); requests are routed through the gateway and credentials are injected automatically — never add Authorization headers.",
      "On errors: `connect_url` → show it to the user and retry after they connect; `blocked_by_policy` → report the rule, do not circumvent; `rate_limited` → wait `retry_after_secs`. Details: onecli-gateway skill.",
      "",
    ].join("\n")
  );
}

async function main(): Promise<void> {
  const hookInput = await readHookInput();
  const sessionId = typeof hookInput.session_id === "string" ? hookInput.session_id : "";
  const envPath = writeLoaderFile(sessionId);

  if (isOnecliProxy(process.env.HTTPS_PROXY)) {
    process.stderr.write("onecli: gateway already active.\n");
    printActiveMessage();
    return;
  }

  const apiKey = resolveApiKey();
  if (!apiKey) {
    process.stderr.write("onecli: no API key found.\n");
    printSetupRequired();
    return;
  }

  process.stderr.write(`onecli: gateway loader written to ${envPath}.\n`);
  printActiveMessage();
}

main().catch((err) => {
  process.stderr.write(
    `onecli: plugin error - ${err instanceof Error ? err.message : String(err)}\n`
  );
});
