#!/usr/bin/env node

// src/codex/session-start.mts
import { dirname as dirname2, join as join2 } from "path";
import { fileURLToPath } from "url";

// src/shared/runtime.mts
import { execSync } from "child_process";
import { chmodSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { createConnection } from "net";
import { homedir } from "os";
import { dirname, join } from "path";
var KEYCHAIN_SERVICE = "onecli-api-key";
function userHome() {
  return process.env.HOME || homedir();
}
function onecliPaths(home = userHome()) {
  const onecliDir = join(home, ".onecli");
  return {
    home,
    onecliDir,
    envPath: join(onecliDir, "env.sh"),
    caBundlePath: join(onecliDir, "ca-bundle.pem"),
    credentialsPath: join(onecliDir, "credentials", "api-key"),
    configPath: join(onecliDir, "config.json"),
    pluginAuthPath: join(home, ".config", "onecli-plugin", "auth.json")
  };
}
function safeReadFile(path) {
  try {
    return readFileSync(path, "utf-8").trim();
  } catch {
    return null;
  }
}
function safeReadJson(path) {
  const content = safeReadFile(path);
  if (!content) return null;
  try {
    return JSON.parse(content);
  } catch {
    return null;
  }
}
function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}
function ensurePrivateDir(path) {
  mkdirSync(path, { recursive: true, mode: 448 });
  try {
    chmodSync(path, 448);
  } catch {
  }
}
function writeFilePrivate(path, content) {
  ensurePrivateDir(dirname(path));
  writeFileSync(path, content, { mode: 384 });
  chmodSync(path, 384);
}
function isOnecliProxy(value) {
  if (!value) return false;
  return value.includes("onecli") || value.includes(":10255") || value.includes("aoc_");
}
function resolveApiKey(paths = onecliPaths()) {
  if (process.env.ONECLI_API_KEY) return process.env.ONECLI_API_KEY;
  const fileKey = safeReadFile(paths.credentialsPath);
  if (fileKey) return fileKey;
  if (process.platform === "darwin") {
    try {
      const result = execSync(
        `security find-generic-password -s "${KEYCHAIN_SERVICE}" -w 2>/dev/null`,
        { encoding: "utf-8", timeout: 3e3 }
      ).trim();
      if (result) return result;
    } catch {
    }
  }
  const pluginAuth = safeReadJson(paths.pluginAuthPath);
  if (pluginAuth?.apiKey) return pluginAuth.apiKey;
  return null;
}
async function readHookInput() {
  if (process.stdin.isTTY) return {};
  let raw = "";
  for await (const chunk of process.stdin) {
    raw += chunk;
  }
  const trimmed = raw.trim();
  if (!trimmed) return {};
  try {
    return JSON.parse(trimmed);
  } catch {
    process.stderr.write("onecli: ignored invalid hook stdin.\n");
    return {};
  }
}

// src/codex/session-start.mts
var SCRIPT_DIR = dirname2(fileURLToPath(import.meta.url));
var PLUGIN_ROOT = process.env.PLUGIN_ROOT || dirname2(SCRIPT_DIR);
var HELPER_PATH = join2(PLUGIN_ROOT, "bin", "onecli-codex-env.mjs");
var NODE_PATH = process.execPath;
function buildLoaderContent({ pluginRoot, helperPath, nodePath, sessionId }) {
  const sessionLine = sessionId ? `export ONECLI_CODEX_SESSION_ID=${shellQuote(sessionId)}` : "unset ONECLI_CODEX_SESSION_ID";
  return [
    "# Generated by the OneCLI Codex plugin.",
    "# This loader contains no gateway credential; sourcing it fetches fresh exports.",
    `export ONECLI_CODEX_PLUGIN_ROOT=${shellQuote(pluginRoot)}`,
    sessionLine,
    `eval "$(ONECLI_CODEX_PLUGIN_ROOT="$ONECLI_CODEX_PLUGIN_ROOT" ONECLI_CODEX_SESSION_ID="\${ONECLI_CODEX_SESSION_ID:-}" ${shellQuote(nodePath)} ${shellQuote(helperPath)} --format sh)"`,
    ""
  ].join("\n");
}
function writeLoaderFile(sessionId) {
  const paths = onecliPaths();
  const content = buildLoaderContent({
    pluginRoot: PLUGIN_ROOT,
    helperPath: HELPER_PATH,
    nodePath: NODE_PATH,
    sessionId
  });
  writeFilePrivate(paths.envPath, content);
  return paths.envPath;
}
function printSetupRequired() {
  process.stdout.write(
    [
      "OneCLI Gateway: installed but not configured. External API calls will fail.",
      "Run the onecli-setup skill to configure the API key, then start a new thread.",
      ""
    ].join("\n")
  );
}
function printActiveMessage() {
  process.stdout.write(
    [
      "OneCLI Gateway active. Call external APIs directly (plain `curl`/`gh`); requests are routed through the gateway and credentials are injected automatically. Never add Authorization headers.",
      "On errors: `connect_url` \u2192 show it to the user and retry after they connect; `blocked_by_policy` \u2192 report the rule, do not circumvent; `rate_limited` \u2192 wait `retry_after_secs`. Details: onecli-gateway skill.",
      ""
    ].join("\n")
  );
}
async function main() {
  const hookInput = await readHookInput();
  const sessionId = typeof hookInput.session_id === "string" ? hookInput.session_id : "";
  const envPath = writeLoaderFile(sessionId);
  if (isOnecliProxy(process.env.HTTPS_PROXY)) {
    process.stderr.write("onecli: gateway already active.\n");
    printActiveMessage();
    return;
  }
  const apiKey = resolveApiKey();
  if (!apiKey) {
    process.stderr.write("onecli: no API key found.\n");
    printSetupRequired();
    return;
  }
  process.stderr.write(`onecli: gateway loader written to ${envPath}.
`);
  printActiveMessage();
}
main().catch((err) => {
  process.stderr.write(
    `onecli: plugin error: ${err instanceof Error ? err.message : String(err)}
`
  );
});
